### ISSUE TITLE
--config-refresh-rate collisions and unit

### ISSUE THREAD

**Issue by langouste** [syfonseq/backoops#1]
Backups iterations are hard code to 3 minutes, this cause collision with the _config-refresh_ thread. If the two threads want to process at the same time, due to collision rates, configuration refresh is skipped.

Maybe we can merge this two thread to avoid this collisions. Only one rate can launch a config-refresh followed by a backup iteration.

There is also a misunderstood with the help include in the command :
`backoops daemon --help` indicate `--config-refresh-rate` in minutes but logs show us that are seconds processed.

**Comment by matthmart** [comment]
The code has been refactored. This changes the way the backups are executed. Now, every 5 minutes, the daemon updates its state (parsing all backup.yml files in watched directories) and executes the backup process immediately after.
Thus, there is no sync issues anymore between the config update and the backup process.

Thank you for your feedback.
